(define (fast-* a n b)
  (cond ((= n 0) b)
        ((= (remainder n 2) 0)  (fast-* (+ a a) (/ n 2) b))
        (else (fast-* a (- n 1) (+ a b))))
)
(define (fast-*2 a n) 
  (cond ((= n 0) 0)
        ((= (remainder n 2) 0)  (fast-*2 (+ a a) (/ n 2)))
        (else (+ a (fast-*2 a (- n 1)))))
)
(fast-* 5 5 0)
(fast-*2 8 90 0)